llm:
  use: openai

anthropic:
  api_key: ...
  model: claude-3-5-sonnet-20240620

openai:
  api_key: ...
  model: gpt-4o

gcp:
  project_id: ...
  location: us-central1
  model: gemini-1.5-pro

jira:
  server: ...
  username: ...
  api_token: ...
